INTERLOK-3199 Add owasp capability into the parent gradle
adaptris-labs/interlok-build-parent pull request #13
Opened 2020-04-14 10:37 UTC by quotidian-ennui

## Motivation

Since owasp dependency checks aren't a built in plugin; it's not entirely obvious how to make it available in the parent gradle; even though the configuration fothe dependency checks is going be
largely similar for all child projects.

## Modification

Using the classname of the plugin we can force its inclusion in the build.gradle with a default `dependencyCheck` configuration which points to the standard include.

## Result

No change; unless they specifically execute `gradle dependencyCheckAnalyze`

## Testing

Modify the build-parent-json-csv project to point to this branch and run `gradle dependencyCheckAnalyze` (it will likely fail due to a new commons-configuration CVE in interlok-ui).

2020-04-14 15:00 UTC, mcwarman requested changes

2020-04-14 15:00 UTC, mcwarman commented on build.gradle
> +  skipConfigurations = [ "interlokJavadocs", "interlokVerify" ,"antJunit"]
I think `interlokWar` will be checked regardless of whether its used, does something like this make sense:
```
skipConfigurations = buildDetails.isIncludeWar() ? [ "interlokJavadocs", "interlokVerify" ,"antJunit" ] : [ "interlokWar", "interlokJavadocs", "interlokVerify" ,"antJunit" ]
```

2020-04-16 13:56 UTC, quotidian-ennui commented on build.gradle
> +  skipConfigurations = [ "interlokJavadocs", "interlokVerify" ,"antJunit"]
Changes as recommended

2020-04-16 14:29 UTC, mcwarman approved these changes

2020-04-16 14:56 UTC, merged